server {
    listen 80;
    listen [::]:80;
    server_name _;
    root /usr/share/nginx/html;

    location = / {
        return 302 /dashboard;
    }

    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
