version: "3.8"
services:
  db:
    image: postgres:14
    container_name: market-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: marketdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: always


#  redisinsight:
#    image: redislabs/redisinsight:latest
#    container_name: redisinsight
#    ports:
#      - "8001:8001"
#    restart: always

  redis-commander:
    image: rediscommander/redis-commander:latest
    platform: linux/amd64
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - redis


  # === Zookeeper ===
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # === kafka ===
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1



#  fastapi:
#    build:
#      context: .
#      dockerfile: docker/Dockerfile  # or wherever your Dockerfile is
#    container_name: fastapi
#    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#      - redis
#    environment:
#      - DATABASE_URL=postgresql://admin:admin@localhost:5432/marketdb
#      - REDIS_URL=redis://redis:6379/0

volumes:
  pgdata:


